### ISSUE TITLE
Please don't close Issues which are not solved. That's not the Idea.

### ISSUE THREAD

**Issue by tekknix** [bigtreetech/Manta-M8P#125] opened 2024-08-08 12:46 UTC
Please don't close Issues which are not solved. That's not the Idea.

Anyhow, i know how to switch off klipper before trying to list my CAN-Bus Devices (sudo systemctl stop klipper.service)

And additional without getting an UUID of the Board i'm not able to flash it via katapult, cause it can't reset to bootloader.

```
tekknix@Reborn2Pro:~/klipper $ python3 ~/klipper/lib/canboot/flash_can.py -q
Resetting all bootloader node IDs...
Checking for canboot nodes...
Query Complete
```

`~/klippy-env/bin/python ~/katapult/scripts/flashtool.py -i can0 -u 212fadcb00b4 -r
`

Where 212fadcb00b4 is the uuid the board offers directly after restart before it's gone away.

Therefore either the CAN-Mapping of PD0/PD1 as CAN - PINs is wrong for my Manta M8p V2.0 or the CAN isn't working at all.

Regards
MoS-tekknix

_Originally posted by @tekknix in https://github.com/bigtreetech/Manta-M8P/issues/124#issuecomment-2275731460_

**Comment by bigtreetech** [comment] 2024-08-08 12:48
Duplicate of #124

**Closed by bigtreetech** 2024-08-08 12:48 UTC
Labels: duplicate
